### ISSUE TITLE
Feature request: Include other trial data fields from Eu clinical trials register

### ISSUE THREAD

**Issue by rodgersk410** [rfhb/ctrdata#10]
Hi, would it also be possible to include the following fields for analysis?

Start Date
![image](https://user-images.githubusercontent.com/14891255/34617287-f68d8350-f208-11e7-8722-07fb035e0274.png)

Results version number, First version publication date, This version publication date, Other versions, Summary report(s) (Yes/No)
![image](https://user-images.githubusercontent.com/14891255/34617276-eda842e8-f208-11e7-9996-714bdd809a19.png)

**Comment by rfhb** [comment]
Hi, thanks. 

(1) When hovering over the "Start Date", the pop up reads for EEA CTAs, "Date study was authorised to proceed". Such a "Start Date" can be calculated, for example like here for EEA CTAs: https://github.com/rfhb/ctrdata/blob/master/vignettes/ctrdata_usage_examples.Rmd#find-trial-start-date (example could be extended for "Outside EU/EEA" trials). Therefore, this feature seems already available. 

(2) The feature request is for information (Results version number, This version publication date, First version publication date, Other versions, Summary report) which would require an additional way of downloading information from the register. What would be the use case for which this information is required? Thanks.

**Comment by rodgersk410** [comment]
For (1), it looks like the Start Date displayed is actually based on the "Date of Competent Authority Decision" of the earliest started CTA.  So it can be calculated.  Thanks.

I'm interested in analyzing whether trial results have been posted on time per https://ec.europa.eu/health/sites/health/files/files/eudralex/vol-10/2012_302-03/2012_302-03_en.pdf

**Comment by rfhb** [comment]
New feature to address (2) is now implemented in version 0.11: From EUCTR, fields "firstreceived_results_date" (a date) and "version_results_history" (text) are now retrieved when calling `ctrLoadQueryIntoDb(query, euctrresults = TRUE)`. Thanks for the suggestion concerning timely posting of trial results.
