### ISSUE TITLE
Shiny app

### ISSUE THREAD

**Issue by machado-t** [rfhb/ctrdata#33]
By any chance, do you know of any shiny app that utilizes this package? While attempting to create one, I found it works perfectly on my local machine, but it fails if published shinyapps.io.
The error appears to originate from ctrLoadQueryIntoDb(), so I suspect this could be linked to the necessary command-line tools.

**Comment by rfhb** [comment]
Thanks - `ctrdata` runs on some servers on the internet where dependencies can be installed. Perhaps `shinyapps.io` lacks external depencies needed for certain registers (`CTGOV`, `EUCTR`, `ISRCTN`; see https://github.com/rfhb/ctrdata#2-command-line-tools-perl-sed-and-php-52-or-higher). Try using `CTGOV2` or `CTIS`, which have no depencies besides R packages that should be provisioned when deploying to `shinyapps.io`.

**Comment by machado-t** [comment]
Indeed using CTGOV2 instead of CTGOV solved the issue.
Thank you very much for your quick help!

> see https://github.com/rfhb/ctrdata#2-command-line-tools-perl-sed-and-php-52-or-higher).

>  (...) These are required for ctrLoadQueryIntoDb(), the main function of package ctrdata (see [Example workflow](https://github.com/rfhb/ctrdata#example-workflow)), to work with the registers EUCTR, CTGOV, ISRCTN (but are not required to work with CTIS); (...)

By the way, you may want to consider mentioning that CTGOV2 also have no dependencies on that section of the readme

**Comment by rfhb** [comment]
@machado-t Today's development version ca7f243378d2700f6d6fabb24d5cf5e591b596f7 should work with all registers in the hosted environment because all dependencies on command line tools were removed, see https://rfhb.github.io/ctrdata/news/index.html#improvements-1-15-2-9002

**Comment by machado-t** [comment]
That's great news! Thank you so much! I will test this soon.
