### ISSUE TITLE
Invalid numeric literal

### ISSUE THREAD

**Issue by amosdejong** [rfhb/ctrdata#34]
Dear Ralf Herold, 

When using your package to retrieve data from the CTIS registry, I encounter the following error message in step 3 (for some narrow queries the error does not occur). Would there be a workaround for this issue?

Best wishes,

Amos de Jong

> ctrLoadQueryIntoDb(
+   queryterm = "", 
+   register = "CTIS",
+   con = ctis_trials
+ )
* Found search query from CTIS: 
* Checking trials in EUCTR...
(1/5) Downloading trials list . . found 400 trials
(2/5) Downloading and processing part I and parts II... (estimate: 60 Mb)
Download status: 400 done; 0 in progress. Total size: 58.97 Mb (100%)... done!             
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
(3/5) Downloading and processing additional data:
publicevents, summary, layperson, csr, cm, inspections, publicevaluation
Error: Invalid numeric literal at line 1, column 38668542

**Comment by rfhb** [comment]
Thanks. Can you please report the package version, e.g. using `utils::packageVersion("ctrdata")`? Please try again using the latest development version as per below. This had several issues fixed, I believe also this type of error. A release is planned for the next days. 

```r
remotes::install_github("rfhb/ctrdata")
<your code>
```

**Comment by rfhb** [comment]
Thanks, this is the latest released, but with the development version it should be ok (I ran similar code a few days ago).

**Comment by rfhb** [comment]
Duplicate of https://github.com/rfhb/ctrdata/issues/31

**Comment by rfhb** [comment]
New release of `ctrdata` 1.16.0 now available on CRAN; for changes see https://rfhb.github.io/ctrdata/news/index.html#ctrdata-1160-released-2023-11-24.
