### ISSUE TITLE
How to cite this package?

### ISSUE THREAD

**Issue by machado-t** [rfhb/ctrdata#35]
Hi! 
Do you have any preference regarding how this package should be cited?

**Comment by rfhb** [comment]
Call in R citation("ctrdata") or see the end of this section: https://rfhb.github.io/ctrdata/#main-features - thanks

**Comment by machado-t** [comment]
Thank you. Sorry I missed that.

**Comment by rfhb** [comment]
No problem and thanks for using ctrdata!
