### ISSUE TITLE
CTIS query seems not to function

### ISSUE THREAD

**Issue by leviohoste** [rfhb/ctrdata#42]
I cannot seem to get the CTIS query functional. 
could it be that the search url that is fetched 
format "https://euclinicaltrials.eu/ct-public-api-services/services/ct/publiclookup/?&paging=0,200&sorting=+ctNumber&" 
is not longer functional?

It gives the following error:
Error in if (tmp$status_code[1] != 200L) { : 
  missing value where TRUE/FALSE needed

**Comment by rfhb** [comment]
Thanks for using the issue tracker! This is related to the recent relaunch of CTIS, which changed the user interface and API; accordingly `ctrdata` was updated just a few days later: https://rfhb.github.io/ctrdata/news/index.html#possibly-breaking-changes-1-19-0 Thus the solution is to install again or update `ctrdata`, e.g. see here: https://rfhb.github.io/ctrdata/articles/ctrdata_install.html#install-package-ctrdata-on-an-r-system

**Comment by leviohoste** [comment]
That worked perfectly!
Thank you very much for your rapid response and for the development of this
great package!!

Levi

*Levi Hoste*
Sparrenstraat 8 - 9840 De Pinte
*T* +32 472 931 861
*E*
***@***.*** ***@***.***>*


Op do 18 jul 2024 om 13:23 schreef Ralf Herold ***@***.***>:
