### ISSUE TITLE
Error: no such function: jsonb_extract

### ISSUE THREAD

**Issue by kdobinda** [rfhb/ctrdata#43]
Tried to run the example code using clipboard, and kept getting the error: Error: no such function: jsonb_extract. Reproduced the error on a different device. All packages are up to date. Here is my code:

> library("ctrdata")
> 
> # in clipboard: https://clinicaltrials.gov/study/NCT03515837
> q <- ctrGetQueryUrl()
* Using clipboard content as register query URL: https://clinicaltrials.gov/study/NCT03515837
* Appears specific for CTGOV REST API 2.0
* Found search query from CTGOV2: id=NCT03515837
> 
> db <- nodbi::src_sqlite(
+   dbname = "some_database_name.sqlite_file",
+   collection = "some_collection_name"
+ )
> 
> # Retrieve trials from public register:
> ctrLoadQueryIntoDb(
+   queryterm = q,
+   euctrresults = TRUE,
+   con = db
+ )
* Checking trials using CTGOV REST API 2.0, found 1 trials
(1/3) Downloading in 1 batch(es) (max. 1000 trials each; estimate: 0.1 Mb total)
(2/3) Converting to NDJSON...
(3/3) Importing records into database...
Warning: call dbDisconnect() when finished working with a connection

= Imported or updated 1 trial(s)
Error: no such function: jsonb_extract

**Comment by rfhb** [comment]
Thanks! Could you please run and report the output of the following command from the session that raised the error message? 
```
sessionInfo()
```

**Comment by kdobinda** [comment]
Thanks for getting back to me!

> sessionInfo()
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/Los_Angeles
tzcode source: internal

attached base packages:
[1] stats     graphics 
[3] grDevices utils    
[5] datasets  methods  
[7] base     

other attached packages:
 [1] RJSONIO_1.3-1.9      
 [2] rjson_0.2.21         
 [3] jsonlite_1.8.7       
 [4] ctrdata_1.19.4       
 [5] ggradar_0.2          
 [6] fmsb_0.7.6           
 [7] openxlsx_4.2.5.2     
 [8] pROC_1.18.4          
 [9] writexl_1.4.2        
[10] km.ci_0.5-6          
[11] survminer_0.4.9      
[12] ggpubr_0.6.0         
[13] survival_3.5-7       
[14] gt_0.10.0            
[15] gtsummary_1.7.2      
[16] png_0.1-8            
[17] kableExtra_1.3.4.9000
[18] arsenal_3.6.3        
[19] labelled_2.12.0      
[20] dplyr_1.1.2          
[21] purrr_1.0.1          
[22] readr_2.1.4          
[23] tidyr_1.3.0          
[24] tibble_3.2.1         
[25] ggplot2_3.4.2        
[26] tidyverse_2.0.0      
[27] stringr_1.5.0        
[28] forcats_1.0.0        
[29] broom_1.0.5          
[30] lubridate_1.9.2      
[31] readxl_1.4.3         
[32] knitr_1.43

**Comment by rfhb** [comment]
Ok, please could you redo as follows:  
```
sessionInfo(c("nodbi", "RSQLite"))
```

**Comment by kdobinda** [comment]
> sessionInfo(c("nodbi", "RSQLite"))
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/Los_Angeles
tzcode source: internal

attached base packages:
character(0)

other attached packages:
[1] nodbi_0.10.7 
[2] RSQLite_2.3.1

**Comment by rfhb** [comment]
Ok, the `RSQLite` version is not current but from 2023-04-03 (https://cran.r-project.org/src/contrib/Archive/RSQLite/). It should be updated and in fact, package `nodbi` requires a higher version of `RSQLite`. Thus, I suggest to run either 
```
install.packages("RSQLite")
``` 
or follow the suggestion at https://rfhb.github.io/ctrdata/#sqlite.

**Comment by kdobinda** [comment]
I updated both packages, but now I get this error before even arriving at the previous step:

> library("nodbi")
> library("RSQLite")
> library("ctrdata")
> 
> # in clipboard: https://clinicaltrials.gov/study/NCT03515837
> q <- ctrGetQueryUrl()
* Using clipboard content as register query URL: https://clinicaltrials.gov/study/NCT03515837
* Appears specific for CTGOV REST API 2.0
* Found search query from CTGOV2: id=NCT03515837
> 
> db <- nodbi::src_sqlite(
+   dbname = "some_database_name.sqlite_file",
+   collection = "some_collection_name"
+ )
Error in match.arg(extension) : 
  'arg' should be one of “math”, “regexp”, “series”, “csv”

**Comment by rfhb** [comment]
Ok, this means that the nodbi package was updated to the development version but your system did not update the RSQLite package to the development version. This is a local issue and I cannot help, perhaps you can take a clue from the messages printed during that install. 

So, just revert to the published, working stable versions with this: 
```
install.packages(c("nodbi", "RSQLite"))
```
Subsequently, 
```
sessionInfo(c("nodbi", "RSQLite"))
```
should show version numbers 0.10.7 for nodbi and 2.3.7 for RSQLite. 
These problems are unrelated to `ctrdata`, and I hope you will enjoy using it.

**Comment by rfhb** [comment]
No further feedback received, thus closing.

**Comment by rfhb** [comment]
Addressed through https://github.com/ropensci/nodbi/commit/82284becc0eb158f589200a49bf255d7d831b331 and https://github.com/ropensci/nodbi/commit/8255c2a5d8d46c503f492582592d5fcafbd5b0e3
